site_url: https://fays.al

backend:
  name: github
  repo: hmfaysal/gatsby-blog # Path to your GitHub repository
  branch: main
  base_url: https://decapoauth2.fays.al

media_folder: "content/assets"
public_folder: "/assets"


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    yaml_quote: true
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", yaml_quote: true }
      - { label: "Description", name: "description", widget: "string", yaml_quote: true }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", default: '{{now}}', yaml_quote: true }
      - { label: "Featured Image", name: "cover", widget: "image", yaml_quote: true }
      - { label: "Tags", name: "tags", widget: "list",  yaml_quote: false }
      - { label: "Body", name: "body", widget: "markdown" }